name: Check PR title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ $GITHUB_EVENT_NAME != 'pull_request' ]]; then
            echo "This action should only be run with Pull Request Events"
            exit 1
          fi

          jira_ticket_id=$(echo "$PR_TITLE" | grep -oE '[A-Z]+-[0-9]+')

          if [[ -z $jira_ticket_id ]]; then
            echo "No Jira Ticket ID found"
            exit 1
          fi

          echo "Jira Ticket ID: $jira_ticket_id"
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
