name: Check PR title

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          printenv | more
